### ISSUE TITLE
code styling

### ISSUE THREAD

**Issue by vitaly-t** [Kinectsit/kinects-it#83]
from https://github.com/Kinectsit/kinects-it/blob/master/server/models/userModel.js#L45

the following two code pieces are the same:

``` js
()=>{
   return {
         // properties
    }
}
```

and

``` js
()=>({
   // properties
})
```

;)

**Comment by brnewby602** [comment]
@vitaly-t :  indeed correct :)   With so many fat-arrows it got confusing on the overall function structure, I just need to just get used to es6 syntax
